name: dart_code_metrics_github_action_app
version: 1.0.0
description: Github action app that helps to run dart_code_metrics in CI/CD flow.
homepage: https://github.com/dart-code-checker/run-dart-code-metrics-action
issue_tracker: https://github.com/dart-code-checker/run-dart-code-metrics-action/issues
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_code_metrics:
    git: https://github.com/dart-code-checker/dart-code-metrics.git
  github: ^8.1.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  coverage: ^1.0.2
  mocktail: ^0.1.2
  pedantic: ^1.11.0
  source_span: ^1.8.0
  test: ^1.17.3
