name: action_app
version: 1.0.0
description: Github action app that helps to run dart_code_metrics in CI/CD flow.
homepage: https://github.com/dart-code-checker/dart-code-metrics-action
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics-action/issues
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_code_metrics: ^4.0.2-dev.1
  github: ^8.1.0
  meta: ^1.4.0
  path: ^1.8.0

dev_dependencies:
  coverage: ^1.0.2
  lints: ^1.0.1
  mocktail: ^0.1.4
  source_span: ^1.8.0
  test: ^1.17.3
